#!/bin/sh

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

append_to_bash_profile() {
  echo "$1" >> ~/.bash_profile
}

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

if ! command -v xcode-select >/dev/null; then
  fancy_echo "Looks like we need to install xcode cli tools..."
  
  xcode-select --install
fi

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."

  curl -fsS \
    'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask..."
  
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae and installing software..."

brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "homebrew/services"
tap "caskroom/cask"

brew "node"
brew "ffmpeg"

cask "virtualbox"
cask "slack"
cask "skype"
cask "1password"
cask "sequel-pro
cask "google-drive
cask "google-chrome
cask "firefox
cask "docker
cask "vagrant"
cask "sublime-text"
cask "webstorm"
cask "phpstorm"
cask "pycharm"
cask "tower"
cask "ngrok"

EOF

# Languages
fancy_echo "Lets add some language, but first some version managers..."

brew install nvm
brew install npm

mkdir -p ~/.nvm

# shellcheck disable=SC2016
append_to_bash_profile 'export NVM_DIR="$HOME/.nvm"'
# shellcheck disable=SC2016
append_to_bash_profile '  . "$(brew --prefix nvm)/nvm.sh"'

fancy_echo 'Refreshing...'

source ~/.bash_profile

fancy_echo 'Lets set up Vagrant now'

cd ~ || exit

### Install Vagrant & VirtualBox & Homestead

vagrant box add laravel/homestead
cd Code
git clone https://github.com/laravel/homestead Homestead
cd Homestead
bash init.sh
subl ~/.homestead/Homestead.yaml

# Add to .bash_profile or .zshrc - for easy access to vagrant up
alias homestead='function __homestead() { (cd ~/Homestead && vagrant $*); unset -f __homestead; }; __homestead'

# When changing homestead.yaml file do provision to update settings in vagrant:
homestead provision

start homestead up
stop homestead halt

fancy_echo 'Now you\'re good to go! And welcome to Jiminny'
