#!/bin/sh

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

append_to_bash_profile() {
  echo "$1" >> ~/.bash_profile
}

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC1117,SC2059
  printf "\n$fmt\n" "$@"
}

if ! command -v xcode-select >/dev/null; then
  fancy_echo "Looks like we need to install xcode cli tools..."
  
  xcode-select --install
fi

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."

  curl -fsS \
    'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask..."
  
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae and installing software..."

brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "homebrew/services"
tap "caskroom/cask"

brew "chromedriver"
brew "docker"
brew "ffmpeg"
brew "media-info"
brew "npm"
brew "yarn"

cask "1password"
cask "browserstacklocal"
cask "firefox"
cask "google-chrome"
cask "google-drive-file-stream"
cask "ngrok"
cask "owasp-zap"
cask "phpstorm"
cask "postman"
cask "pycharm"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "sequel-pro"
cask "slack"
cask "skype"
cask "sublime-text"
cask "suspicious-package"
cask "tower"
cask "virtualbox"
cask "vlc"
cask "webstorm"

EOF

fancy_echo "Now you're good to go! And welcome to Jiminny"
