#!/bin/sh
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

append_to_bash_profile() {
    echo "$1" >> ~/.bash_profile
}

echo_info() {
  echo -e "\x1b[1;34m[S] First Boot: $1\e[0m"
}

echo_success() {
  echo -e "\x1b[1;32m[S] First Boot: $1\e[0m"
}

if ! command -v xcode-select >/dev/null; then
    echo "Looks like we need to install xcode cli tools..."

    xcode-select --install
fi

if ! command -v brew >/dev/null; then
    echo "Installing Homebrew ..."

    curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
fi

brew install node
brew install ffmpeg

brew tap caskroom/cask

# Programs

echo "Lets install some software..."

brew cask install virtualbox
brew cask install slack
brew cask install 1password
brew cask install sequel-pro
brew cask install google-chrome
brew cask install firefox
brew cask install docker
brew cask install vagrant
brew cask install sublime-text
brew cask install webstorm
brew cask install phpstorm
brew cask install tower

# Languages

echo "Lets add some language, but first some version managers..."

brew install nvm
brew install npm

mkdir -p ~/.nvm

# shellcheck disable=SC2016
append_to_bash_profile 'export NVM_DIR="$HOME/.nvm"'
# shellcheck disable=SC2016
append_to_bash_profile '  . "$(brew --prefix nvm)/nvm.sh"'

echo 'Refreshing...'

source ~/.bash_profile

echo 'Lets set up Vagrant now'

cd ~ || exit

### Install Vagrant & VirtualBox & Homestead

vagrant box add laravel/homestead
cd Code
git clone https://github.com/laravel/homestead Homestead
cd Homestead
bash init.sh
subl ~/.homestead/Homestead.yaml

# Add to .bash_profile or .zshrc - for easy access to vagrant up
alias homestead='function __homestead() { (cd ~/Homestead && vagrant $*); unset -f __homestead; }; __homestead'

# When changing homestead.yaml file do provision to update settings in vagrant:
homestead provision

start homestead up
stop homestead halt

echo 'Now your good to go! And welcome to Jiminny'
